In [1]:
import pandas as pd
sale=pd.read_csv(r"C:\Users\hp\Documents\prasanna-pandas\Sales.csv")
sale

                    Date   SKU                Product Name        City  Sales
0     2023-01-01 0:00:00  F001             Prateek England      Mumbai     93
1     2023-01-01 0:00:00  F002               Lucy Phillepe      Mumbai     36
2     2023-01-01 0:00:00  F003                    Badlands      Mumbai      7
3     2023-01-01 0:00:00  F004                 Allen Dolly      Mumbai     55
4     2023-01-01 0:00:00  F005                      Bucchi      Mumbai     41
...                  ...   ...                         ...         ...    ...
6195  2023-01-30 0:00:00  G001           Crafting Chandlar  Aurangabad     13
6196  2023-01-30 0:00:00  G002                  Desi Kurti  Aurangabad     24
6197  2023-01-30 0:00:00  G003  Family Cake and Card Combo  Aurangabad     66
6198  2023-01-30 0:00:00  G004           Exact Flower Vase  Aurangabad     55
6199  2023-01-30 0:00:00  G005          Friends Dinner Set  Aurangabad     59

[6200 rows x 5 columns]

In [2]:
df_s=sale.groupby('City')['Sales'].sum()
df_s

City
Aurangabad    35853
Mumbai        76946
Nasik         47959
Pune          43422
Name: Sales, dtype: int64

In [3]:
df_s1=sale.groupby(['City','Product Name'])['Sales'].sum()
df_s1

City        Product Name
Aurangabad  2plus                              407
            4 states                           777
            Abibas Football                    757
            Allen Dolly                        556
            Amazing CornFlakes                2091
                                              ...
Pune        Story of Your Life                 671
            SureIt Purifier                    562
            Tata Yellow Label                 1448
            Yamaka Rex 5000W Mixer Grinder     587
            Yoga Mattress                      564
Name: Sales, Length: 200, dtype: int64

In [4]:
df_s2=pd.pivot_table(sale,values='Sales',index='City',columns='Product Name',aggfunc='sum')
df_s2

Product Name,2plus,4 states,Abibas Football,Allen Dolly,Amazing CornFlakes,Badlands,Blessing Atta 10kg pack,Bucchi,Crafting Chandlar,Descafe Gold Blend coffee,...,Rural Terrain Cycles,Samson,Screw Activity Watch,Shaktiman Returns,Softcare Electric Toothbrush,Story of Your Life,SureIt Purifier,Tata Yellow Label,Yamaka Rex 5000W Mixer Grinder,Yoga Mattress
City,,,,,,,,,,,,,,,,,,,,,
Aurangabad,407,777,757,556,2091,508,2492,404,966,1782,...,344,442,345,826,187,646,403,1617,519,633
Mumbai,609,1439,891,1362,3412,1623,4411,1710,1753,3264,...,419,572,622,1461,414,1255,691,3922,802,756
Nasik,365,689,483,1307,2532,1607,2416,1308,1227,2028,...,383,413,375,623,456,1149,513,2583,457,442
Pune,465,853,813,824,1381,856,1362,838,1389,1466,...,414,411,598,779,451,671,562,1448,587,564

In [5]:
df_s3=sale.groupby(['SKU','City','Product Name'])['Sales'].sum()
df_s3

SKU   City        Product Name
B001  Aurangabad  Harry putar       617
      Mumbai      Harry putar      1331
      Nasik       Harry putar       613
      Pune        Harry putar       846
B002  Aurangabad  4 states          777
                                   ...
V004  Pune        LTA Wise City    1244
V005  Aurangabad  HIFA 2023        1024
      Mumbai      HIFA 2023        2668
      Nasik       HIFA 2023         988
      Pune        HIFA 2023        1186
Name: Sales, Length: 200, dtype: int64

In [6]:
#-------------------SKU MASTER----------------

In [20]:
import pandas as ps
sku=ps.read_csv(r"C:\Users\hp\Documents\prasanna-pandas\SKU MASTER.csv")
sku

      SKU                     Description              Category  Price
0    F001                 Prateek England              Fashion    1140
1    F002                   Lucy Phillepe              Fashion    2596
2    F003                        Badlands              Fashion    1395
3    F004                     Allen Dolly              Fashion    2700
4    F005                          Bucchi              Fashion    8400
5    M001                          Jhaomi               Mobiles  24300
6    M002                          Samson               Mobiles  26250
7    M003                           Mokia               Mobiles  12150
8    M004                        Hotorola               Mobiles  44500
9    M005                           2plus               Mobiles  31950
10   B001                    Harry putar                  Books   2730
11   B002                       4 states                  Books    847
12   B003               Shaktiman Returns                 Books    200
13   B004                   Goli's Travel                 Books    720
14   B005              Story of Your Life                 Books   1120
15   V001             Prince of Dholakpur          Video Games    1144
16   V002                           Nario          Video Games     627
17   V003                          Pacman          Video Games     110
18   V004                   LTA Wise City          Video Games    2875
19   V005                       HIFA 2023          Video Games    2247
20   S001                Abibas Football       Sports / Fitness   2850
21   S002            Rural Terrain Cycles      Sports / Fitness  12720
22   S003         Monex Badminton Rackets      Sports / Fitness   5700
23   S004                   Yoga Mattress      Sports / Fitness    858
24   S005                   Rocky Gym Set      Sports / Fitness  12600
25  ME001                 Pyllum Trimmers  Medicines/Healthcare   1859
26  ME002    Softcare Electric Toothbrush  Medicines/Healthcare   1540
27  ME003                    Leg Messager  Medicines/Healthcare  15390
28  ME004            NoFat Weighing Scale  Medicines/Healthcare    809
29  ME005            Screw Activity Watch  Medicines/Healthcare   1596
30   K001                 SureIt Purifier              Kitchen    5550
31   K002          Parrot Induction Stove              Kitchen    1995
32   K003             Jalepenoware Tiffin              Kitchen     320
33   K004  Yamaka Rex 5000W Mixer Grinder              Kitchen     801
34   K005             Mr.Clean Dishwasher              Kitchen   15064
35   H001         Blessing Atta 10kg pack           Household      428
36   H002              Amazing CornFlakes           Household      216
37   H003               Tata Yellow Label           Household      672
38   H004       Descafe Gold Blend coffee           Household      690
39   H005           Handmade Basmati Rice           Household      880
40   P001               Podigree Dog Food          Pet Supplies   1316
41   P002                   Matty Dog Bed          Pet Supplies   8049
42   P003          Park Range Pet Shampoo          Pet Supplies   1378
43   P004           Old Mint Pet Shampoos          Pet Supplies   1404
44   P005         Reflective Dog RainCoat          Pet Supplies   3776
45   G001              Crafting Chandlar                Gifting   1680
46   G002                      Desi Kurti               Gifting   2088
47   G003      Family Cake and Card Combo               Gifting   1130
48   G004               Exact Flower Vase               Gifting   4200
49   G005              Friends Dinner Set               Gifting   5460

In [21]:
sku.Category.unique()

array(['Fashion ', 'Mobiles', 'Books', 'Video Games ', 'Sports / Fitness',
       'Medicines/Healthcare', 'Kitchen ', 'Household  ', 'Pet Supplies',
       'Gifting'], dtype=object)

In [22]:
df_sku1=sku.groupby(['Category'])['Price'].sum()
df_sku1

Category
Books                     5617
Fashion                  16231
Gifting                  14558
Household                 2886
Kitchen                  23730
Medicines/Healthcare     21194
Mobiles                 139150
Pet Supplies             15923
Sports / Fitness         34728
Video Games               7003
Name: Price, dtype: int64

In [23]:
def price_discount(Category,Price):
    if Category=="Books":
        discount=Price*0.10
        after_dis=Price-discount
    elif Category=="Fashion":
        discount=Price*0.30
        after_dis=Price-discount
    elif Category=="Gifting":
        discount=Price*0.40
        after_dis=Price-discount
    elif Category=="Household":
        discount=Price*0.40
        after_dis=Price-discount
    elif Category=="Kitchen":
        discount=Price*0.30
        after_dis=Price-discount
    elif Category=="Medicines/Healthcare":
        discount=Price*0.30
        after_dis=Price-discount
    elif Category=="Mobiles":
        discount=Price*0.30
        after_dis=Price-discount
    elif Category=="Pet Supplies":
        discount=Price*0.20
        after_dis=Price-discount
    elif Category=="Sports / Fitness":
        discount=Price*0.40
        after_dis=Price-discount
    elif Category=="Video Games":
        discount=Price*0.10
        after_dis=Price-discount
    return after_dis

In [38]:
price_discount("Sports / Fitness",34728)

20836.8

In [39]:
data={"Category":['Books','Fashion','Gifting','Household','Kitchen','Medicines/Healthcare','Mobiles','Pet Supplies','Sports / Fitness','Video Games'],
      "Price":[5617,16231,14558,2886,23730,21194,139150,15923,34728,7003],
     "Discount":[5055,11362,8735,1732,16611,14836,97405,12738,2083.8,6302]}
df = ps.DataFrame(data)
df

               Category   Price  Discount
0                 Books    5617    5055.0
1               Fashion   16231   11362.0
2               Gifting   14558    8735.0
3             Household    2886    1732.0
4               Kitchen   23730   16611.0
5  Medicines/Healthcare   21194   14836.0
6               Mobiles  139150   97405.0
7          Pet Supplies   15923   12738.0
8      Sports / Fitness   34728    2083.8
9           Video Games    7003    6302.0

In [18]:
# ---------table-2-----scenario2

In [11]:
df_sku2=sku.groupby(['Description','Category'])['Price'].sum()
df_sku2

Description                     Category
2plus                           Mobiles                 31950
4 states                        Books                     847
Abibas Football                 Sports / Fitness         2850
Allen Dolly                     Fashion                  2700
Amazing CornFlakes              Household                 216
Badlands                        Fashion                  1395
Blessing Atta 10kg pack         Household                 428
Bucchi                          Fashion                  8400
Crafting Chandlar               Gifting                  1680
Descafe Gold Blend coffee       Household                 690
Desi Kurti                      Gifting                  2088
Exact Flower Vase               Gifting                  4200
Family Cake and Card Combo      Gifting                  1130
Friends Dinner Set              Gifting                  5460
Goli's Travel                   Books                     720
HIFA 2023                       Video Games              2247
Handmade Basmati Rice           Household                 880
Harry putar                     Books                    2730
Hotorola                        Mobiles                 44500
Jalepenoware Tiffin             Kitchen                   320
Jhaomi                          Mobiles                 24300
LTA Wise City                   Video Games              2875
Leg Messager                    Medicines/Healthcare    15390
Lucy Phillepe                   Fashion                  2596
Matty Dog Bed                   Pet Supplies             8049
Mokia                           Mobiles                 12150
Monex Badminton Rackets         Sports / Fitness         5700
Mr.Clean Dishwasher             Kitchen                 15064
Nario                           Video Games               627
NoFat Weighing Scale            Medicines/Healthcare      809
Old Mint Pet Shampoos           Pet Supplies             1404
Pacman                          Video Games               110
Park Range Pet Shampoo          Pet Supplies             1378
Parrot Induction Stove          Kitchen                  1995
Podigree Dog Food               Pet Supplies             1316
Prateek England                 Fashion                  1140
Prince of Dholakpur             Video Games              1144
Pyllum Trimmers                 Medicines/Healthcare     1859
Reflective Dog RainCoat         Pet Supplies             3776
Rocky Gym Set                   Sports / Fitness        12600
Rural Terrain Cycles            Sports / Fitness        12720
Samson                          Mobiles                 26250
Screw Activity Watch            Medicines/Healthcare     1596
Shaktiman Returns               Books                     200
Softcare Electric Toothbrush    Medicines/Healthcare     1540
Story of Your Life              Books                    1120
SureIt Purifier                 Kitchen                  5550
Tata Yellow Label               Household                 672
Yamaka Rex 5000W Mixer Grinder  Kitchen                   801
Yoga Mattress                   Sports / Fitness          858
Name: Price, dtype: int64

In [59]:
def discount_price(Description,Category,Price):
    if Description=="Allen Dolly":
        if Category=="Fashion":
            discount=Price*0.30
            after_dis=Price-discount
    elif Description=="Bucchi":
        if Category=="Fashion":
            discount=Price*0.30
            after_dis=Price-discount
    elif Description=="Shaktiman Returns":
        if Category=="Books":
            discount=Price*0.30
            after_dis=Price-discount
    elif Description=="Goli's Travel":
        if Category=="Books":
            discount=Price*0.30
            after_dis=Price-discount
    elif Description=="LTA Wise City":
        if Category=="Video Games":
            discount=Price*0.30
            after_dis=Price-discount
    elif Description=="HIFA 2023":
        if Category=="Video Games":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Rocky Gym Set":
        if Category=="Sports / Fitness":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Pyllum Trimmers":
        if Category=="Medicines/Healthcare":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Mr.Clean Dishwasher":
        if Category=="Kitchen":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Blessing Atta 10kg pack":
        if Category=="Household":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Amazing CornFlakes":
        if Category=="Household":
            discount=Price*0.40
            after_dis=Price-discount
    elif Description=="Tata Yellow Label":
        if Category=="Household":
            discount=Price*0.50
            after_dis=Price-discount
    elif Description=="Old Mint Pet Shampoos":
        if Category=="Pet Supplies":
            discount=Price*0.50
            after_dis=Price-discount
    elif Description=="Reflective Dog RainCoat":
        if Category=="Pet Supplies":
            discount=Price*0.50
            after_dis=Price-discount
    elif Description=="Crafting Chandlar":
        if Category=="Gifting":
            discount=Price*0.60
            after_dis=Price-discount
    elif Description=="Desi Kurti":
        if Category=="Gifting":
            discount=Price*0.60
            after_dis=Price-discount
    return after_dis

In [60]:
discount_price("Reflective Dog RainCoat","Pet Supplies",3776)

1888.0

In [64]:
condition={"Description":["Allen Dolly","Bucchi","Shaktiman Returns","Goli's Travel","LTA Wise City","HIFA 2023","Rocky Gym Set","Pyllum Trimmers","Mr.Clean Dishwasher","Blessing Atta 10kg pack","Amazing CornFlakes","Tata Yellow Label","Old Mint Pet Shampoos","Reflective Dog RainCoat","Crafting Chandlar","Desi Kurti"],
      "Category":["Fashion","Fashion","Books","Books","Video Games","Video Games","Sports / Fitness","Medicines/Healthcare","Kitchen","Household","Household","Household","Pet Supplies","Pet Supplies","Gifting","Gifting"],
      "Price":[2700,8400,200,720,2872,2247,12600,1859,15064,428,216,672,1404,3776,1680,2088],
      "price_discount":[1890,5880,140,504,2010.4,1348.12,7560,1115.4,9038.4,256.79,129.6,313.5,702.0,1888.0,672.0,853.2]}
df_stock = ps.DataFrame(condition)
df_stock

                Description              Category  Price  price_discount
0               Allen Dolly               Fashion   2700         1890.00
1                    Bucchi               Fashion   8400         5880.00
2         Shaktiman Returns                 Books    200          140.00
3             Goli's Travel                 Books    720          504.00
4             LTA Wise City           Video Games   2872         2010.40
5                 HIFA 2023           Video Games   2247         1348.12
6             Rocky Gym Set      Sports / Fitness  12600         7560.00
7           Pyllum Trimmers  Medicines/Healthcare   1859         1115.40
8       Mr.Clean Dishwasher               Kitchen  15064         9038.40
9   Blessing Atta 10kg pack             Household    428          256.79
10       Amazing CornFlakes             Household    216          129.60
11        Tata Yellow Label             Household    672          313.50
12    Old Mint Pet Shampoos          Pet Supplies   1404          702.00
13  Reflective Dog RainCoat          Pet Supplies   3776         1888.00
14        Crafting Chandlar               Gifting   1680          672.00
15               Desi Kurti               Gifting   2088          853.20

In [ ]:
#-----------SKU Transfer--------

In [2]:
import pandas as pd
df_sku=pd.read_csv(r"C:\Users\hp\Documents\prasanna-pandas\STOCK TRANSFER_1.csv")
df_sku

,SKU,01-01-2023 00:00,02-01-2023 00:00,03-01-2023 00:00,04-01-2023 00:00,05-01-2023 00:00,06-01-2023 00:00,07-01-2023 00:00,08-01-2023 00:00,09-01-2023 00:00,...,21-01-2023 00:00.2,22-01-2023 00:00.2,23-01-2023 00:00.2,24-01-2023 00:00.2,25-01-2023 00:00.2,26-01-2023 00:00.2,27-01-2023 00:00.2,28-01-2023 00:00.2,29-01-2023 00:00.2,30-01-2023 00:00.2
0,F001,18,25,21,20,18,19,18,16,23,...,41,54,47,45,57,50,56,50,51,53
1,F002,20,28,28,19,29,16,18,27,29,...,49,42,53,47,47,52,53,55,52,51
2,F003,29,26,28,19,19,23,26,27,24,...,54,60,53,49,44,55,47,46,50,44
3,F004,22,28,20,24,24,17,20,19,26,...,49,60,55,51,51,42,48,50,49,51
4,F005,19,21,20,23,27,24,21,20,24,...,52,44,56,43,50,53,46,54,47,43
5,M001,25,19,27,24,29,17,22,26,24,...,27,24,25,22,27,27,21,20,19,22
6,M002,22,21,27,18,23,30,23,28,20,...,21,21,20,18,18,20,26,21,27,20
7,M003,26,28,27,20,23,16,32,23,16,...,19,19,23,23,22,20,20,20,23,23
8,M004,25,18,21,17,20,25,28,26,25,...,20,25,19,20,27,26,22,18,23,20
9,M005,34,17,24,27,24,30,31,23,29,...,24,18,19,24,19,22,20,21,17,18
10,B001,70,24,63,45,54,58,27,61,50,...,30,24,28,30,25,24,26,40,30,25
11,B002,38,66,55,37,33,67,64,31,29,...,21,31,29,32,30,24,36,32,36,31
12,B003,47,28,74,26,25,68,57,20,18,...,22,31,36,39,39,23,25,32,38,28
13,B004,22,44,52,28,70,58,40,19,31,...,35,31,32,26,33,32,34,22,30,29
14,B005,43,41,44,44,38,39,42,47,46,...,46,46,41,37,40,40,48,38,48,42
15,V001,52,31,73,29,71,28,19,60,19,...,40,40,49,48,43,38,36,45,49,45
16,V002,58,64,55,51,66,65,63,63,59,...,48,42,35,40,38,35,36,43,37,51
17,V003,53,55,58,60,67,54,58,61,64,...,39,50,40,38,42,47,38,42,45,47
18,V004,62,63,60,66,51,65,57,64,62,...,45,36,46,35,43,34,44,37,42,46
19,V005,70,41,62,55,53,68,24,76,44,...,39,37,33,38,46,38,48,41,44,37
20,S001,23,46,16,25,34,30,35,33,43,...,18,27,27,25,23,25,21,21,19,28
21,S002,25,24,25,28,26,22,21,20,18,...,21,16,20,27,23,21,21,19,19,20
22,S003,22,23,26,24,31,34,29,32,19,...,28,24,26,29,21,22,26,21,24,17
23,S004,19,41,29,41,26,45,38,20,39,...,25,24,27,23,24,26,21,23,26,25
24,S005,23,19,16,22,23,24,24,18,20,...,26,22,20,18,25,20,22,27,25,24
25,ME001,27,19,31,17,21,29,22,24,35,...,19,18,26,24,27,18,17,28,24,25
26,ME002,28,31,26,32,19,37,22,22,23,...,18,21,20,17,18,25,22,17,27,20
27,ME003,24,38,27,33,29,29,17,22,38,...,26,22,23,19,28,19,20,25,27,17
28,ME004,29,28,32,24,28,23,19,29,30,...,28,19,23,25,28,18,21,18,26,18
29,ME005,34,20,30,29,17,25,24,27,22,...,26,21,25,22,19,29,21,23,22,21
30,K001,33,23,22,23,25,24,20,35,26,...,26,19,19,20,21,22,19,21,24,20
31,K002,37,29,17,27,29,17,39,21,26,...,27,21,26,20,27,25,22,22,24,22
32,K003,19,35,23,19,37,25,30,23,23,...,25,24,24,24,23,20,28,20,19,21
33,K004,26,25,20,26,28,36,27,24,33,...,22,24,16,19,22,24,23,21,23,17
34,K005,23,29,34,31,25,21,22,18,19,...,26,23,29,28,26,32,29,24,29,28
35,H001,41,75,67,73,78,77,71,75,74,...,71,67,78,69,74,70,71,71,69,72
36,H002,23,75,35,18,42,63,21,44,41,...,82,84,96,96,81,80,84,80,84,80
37,H003,28,51,28,64,53,51,69,77,68,...,87,87,84,89,91,94,92,86,85,94
38,H004,36,36,41,76,45,37,63,72,35,...,90,83,78,89,92,93,94,88,84,84
39,H005,63,58,42,46,68,57,65,34,68,...,85,80,81,86,88,94,89,78,95,87
40,P001,62,66,42,42,62,40,61,51,41,...,53,49,43,42,44,53,53,48,54,59
41,P002,64,59,38,66,40,59,43,51,65,...,38,51,37,40,55,50,55,52,47,47
42,P003,61,58,63,50,39,40,48,41,41,...,52,46,41,48,44,50,52,53,53,41
43,P004,49,46,65,40,40,55,43,61,44,...,50,49,56,45,50,55,57,38,56,55
44,P005,63,60,56,52,47,62,59,59,65,...,54,57,37,42,52,50,53,55,55,49
45,G001,58,52,29,28,70,39,50,25,73,...,56,41,57,54,52,40,48,47,54,46
46,G002,51,22,53,22,32,38,32,61,29,...,35,44,32,42,35,50,44,42,45,40
47,G003,61,49,25,17,25,61,24,54,49,...,40,44,44,38,32,44,44,49,46,39
48,G004,18,68,27,30,71,50,22,75,51,...,47,45,43,34,33,39,36,36,35,41
49,G005,23,18,22,71,66,34,43,29,61,...,41,42,42,46,36,32,45,47,42,42

In [3]:
allDates = pd.date_range('01-01-2023 00:00', '30-01-2023 00:00.2', freq ='W')
allDates

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29'],
              dtype='datetime64[ns]', freq='W-SUN')

In [4]:
series = allDates.to_series()
series

2023-01-01   2023-01-01
2023-01-08   2023-01-08
2023-01-15   2023-01-15
2023-01-22   2023-01-22
2023-01-29   2023-01-29
Freq: W-SUN, dtype: datetime64[ns]